### PR TITLE
Map JS name to python name for Vue component attributes

### PR DESCRIPTION
**Pull request by cardinalgeo**
Should simplify setting the LMap max and min zoom parameters (i.e., set maximum and minimum zoom level beyond which no new tiles are served)

(And accidentally deleted the paddingBottomRight param; added it back though!)

### CODE REVIEW

**Comment by jourdain** [comment]
Thanks @cardinalgeo but I was thinking for consistency to do that for all the params. Doing it for only those 2 would make things worse than before.  We should either embrace the current camelCase that is working and that is functional or fix all of the params (on every classes) to follow Python snake_case approach. Hope that make sense, and sorry if I was not clear initially.

**Comment by cardinalgeo** [comment]
Roger that — I had seen a few cases of the JS-to-Python mapping elsewhere in that file, so it seemed adding a few more wouldn't be unreasonable haha. But I'll give this a go again early this week and let you know if I run into issues!

**Comment by cardinalgeo** [comment]
Hi @jourdain, I've made additional changes aligned with your request — hopefully that does the trick! One question though. Should I touch the camelCase in `"update_latLng"` found on line 299 ([here](https://github.com/Kitware/trame-leaflet/blob/master/trame_leaflet/widgets/leaflet.py#L299-L300))? I don't see any indication in the [Vue Leaflet documentation](https://vue2-leaflet.netlify.app/components/LMarker.html#props) that `lat-lng` is something distinct from `latLng`, and so I don't quite understand why lines 299 and 300 are not collapsed into one!

**Comment by jourdain** [comment]
Looks great and you are right, there is no difference between 299-300. One can be removed.

**Comment by jourdain** [comment]
Do you want to fix that line or should I just merge your work?

**Comment by cardinalgeo** [comment]
Just fixed it! Thanks for the guidance :)

**Comment by jourdain** [comment]
You need to run `black` but it might be good to run the rest of the `pre-commit` hooks like describe [here](https://github.com/Kitware/trame-cookiecutter/blob/master/%7B%7Bcookiecutter.package_name%7D%7D/CONTRIBUTING.rst). Actually we should add that file in that current repo.

**Comment by jourdain** [comment]
Thanks for your contribution and that new 1.1.0 release!

**Comment by cardinalgeo** [comment]
Thanks for the suggestions, and glad I could help!

**Pull request merged**
